bulletin/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name= 'bulletin'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout/$', auth_views.logout,{'next_page': '/bulletin'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^notices/$', views.notice, name='notices'),
    url(r'^notices/(?P<notice_id>[0-9]+)/$', views.notice_detail, name='notice_detail'),
    url(r'^students/$', views.student, name='students'),
    url(r'^students/(?P<student_id>[0-9]+)/$', views.student_detail, name='student_detail'),
    url(r'^categories/$', views.category, name='categories'),
    url(r'^categories/(?P<category_id>[0-9]+)/$', views.category_notice, name='category_notice'),
    url(r'^students/(?P<student_id>[0-9]+)/subscribed/$', views.subscription, name='subscription'),
    url(r'^students/(?P<student_id>[0-9]+)/starred/$', views.starred, name='starred'),
]

prozero/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bulletin/', include('bulletin.urls')),
]

bulletin/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Notice(models.Model):
    upload = models.DateTimeField(auto_now_add=True)
    subject = models.CharField(max_length=40)
    content = models.CharField(max_length=300)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    expiry_date =  models.DateTimeField('expiry date')
    def __str__(self):              # __unicode__ on Python 2
        return self.subject

 
class Student(models.Model):
    user = models.OneToOneField(User)
    branch =  models.CharField(max_length=40)
    enr_no = models.IntegerField(default=0)
    def __str__(self):  
          return "%s's profile" % self.user

class Category(models.Model):
    name = models.CharField(max_length=40)
    suscriber = models.ManyToManyField(Student, through='Subscription')
    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Subscription(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subs_since = models.DateTimeField(auto_now=True)

class SNlink(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    star  = models.BooleanField()
    read  = models.BooleanField()

class CNlink(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

bulletin/forms.py
from django import forms

class Login(forms.Form):
    username = forms.CharField(max_length=40)
    password = forms.CharField(widget=forms.PasswordInput)

class Register(forms.Form):
	username = forms.CharField(max_length=20)
	password = forms.CharField(max_length=20)
	email = forms.EmailField()
	first_name = forms.CharField(max_length=20)
	last_name = forms.CharField(max_length=20)
	branch = forms.CharField()
	enr_no = forms.IntegerField()

bulletin/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.contrib.auth import authenticate, login, logout
from .forms import *
from django.urls import reverse
from django.template import loader
from django.shortcuts import render
from datetime import datetime
from django.contrib.auth.decorators import login_required

def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('bulletin:notices'))
    if request.method == 'POST':
	form = Login(request.POST)
	if form.is_valid():
	    username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
	    if user is not None:
                login(request, user)
		return HttpResponseRedirect(reverse('bulletin:notices'))
	    else :
		return HttpResponse("Input Invalid")
    else:
        form = Login()
    	return render(request, 'bulletin/index.html',{'form':form,})

def logout(request):
    logout(request)
    return render(request, 'bulletin/logout.html')

@login_required(login_url='/bulletin/')
def notice(request):
	""" 
	Returns the lists of notices in sorted order
	"""
	latest_notice_list = Notice.objects.order_by('-upload')
	template = loader.get_template('bulletin/notices.html')
	context = {
	    'latest_notice_list': latest_notice_list,
	}
	return HttpResponse(template.render(context, request))
	

@login_required(login_url='/bulletin/')
def notice_detail(request, notice_id):
        notice = get_object_or_404(Notice, pk=notice_id)
	expirydate= notice.expiry_date
	if datetime.today() > expirydate:
	    status = 'expired'
	else:
	    status= 'active'
	return render(request, 'bulletin/notice_detail.html', {'notice': notice, 'status':status})
	
@login_required(login_url='/bulletin/')
def student(request):
    student_list = Student.objects.all().order_by('enr_no')
    template = loader.get_template('bulletin/students.html') 
    context = {                                           
        'student_list': student_list,         
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/bulletin/')
def student_detail(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    return render(request, 'bulletin/student_detail.html', {'student': student}) 

@login_required(login_url='/bulletin/')
def category(request):
    category_list = Category.objects.all().order_by('name')
    template = loader.get_template('bulletin/categories.html')
    context = {
        'category_list': category_list,
    }
    return HttpResponse(template.render(context, request))    

@login_required(login_url='/bulletin/')
def category_notice(request,category_id):
    category = get_object_or_404(Category, pk=category_id)
    notice_list = Notice.objects.all().filter(category = category_id)
    template = loader.get_template('bulletin/category_notice.html')
    context = {                                           
       'notice_list': notice_list,         
    }
    return HttpResponse(template.render(context, request))


@login_required(login_url='/bulletin/')
def subscription(request,student_id):
    subscribed_list = Subscription.objects.all().filter(student__id = student_id)
    template = loader.get_template('bulletin/subscribed.html')
    context = {                                           
        'subscribed_list': subscribed_list,         
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/bulletin/')
def starred(request,student_id):
    notice_list = SNlink.objects.all().filter(student__id = student_id)
    template = loader.get_template('bulletin/starred.html')
    context = {                                           
        'notice_list': notice_list,         
    }
    return HttpResponse(template.render(context, request))	

def register(request):
    if request.method == 'POST':
	form = Register(request.POST)
        if form.is_valid():
	    username = form.cleaned_data['username']
       	    password = form.cleaned_data['password']
            email = form.cleaned_data['email']
       	    first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            branch = form.cleaned_data['branch']
            enr_no = form.cleaned_data['enr_no']
	    user = User(username=username,password=password,email=email,first_name=first_name,last_name=last_name)
	    user.save()
            user_details = UserDetail(user=user,branch=branch,enr_no=enr_no)
	    user_details.save()
            login(request, user)
	    return HttpResponseRedirect(reverse('bulletin:register'))
	else:        
            return render(request, 'bulletin.html')
    else:
	form = Register(request.POST)
        return render(request, 'bulletin/register.html')

bulletin/templates/bulletin/categories.html
{% if category_list %}
    <h2>Category-></h2>
    <br>
    <ol>
    {% for category in category_list %}
        <li> <a href="/bulletin/categories/{{ category.id }}/"> {{ category.name }} </a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No  category is  available.</p>
{% endif %}

bulletin/templates/bulletin/category_notice.html
{% if notice_list %}
    <h1>Notices</h1>
    <ol>
    {% for notice in notice_list %}
       <h3>{{ notice.category }}</h3>
	<li> {{notice.upload}} <a href= "/bulletin/notices/{{ notice.id}}/" >  : {{notice.subject }}</a></li>

    {% endfor %}
    </ol>
    {% else %}
	<p> No NOtice available</p>
{% endif %}

bulletin/templates/bulletin/index.html
<h1>Welcome to BulletinBoard</h1>

<div>
<h3>Login></h3>
<form action="{% url 'bulletin:index' %}" method="post">
	{% csrf_token %}
	{{form}}
	<input type="submit" name="submit">
</form>
</div>

<a href='/bulletin/register'>Register</a>

bulletin/templates/bulletin/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

bulletin/templates/bulletin/logout.html
you are logged out

bulletin/templates/bulletin/notice_detail.html
<h1>{{ notice.subject }}</h1>
<h3>Uploaded by:<a href="/bulletin/categories/{{ notice.category.id}}"> {{ notice.category }} </a></h3>
<h3>status: {{ status  }}</h3>
<h3>posted: {{ notice.upload }}</h3>
<p>{{ notice.content }} </p>

bulletin/templates/bulletin/notices.html
<h1>Notices</h1>
{% if request.user.is_superuser %}
<a <a href="/bulletin/students/ ">All users</a><br>
<a>Upload notices</a><br>
{% else %}
<a href="/bulletin/students/{{request.user.id}}" >Profile</a><br>
{% endif %}
<a href="{% url 'bulletin:logout' %}">logout</a><br>
<a href="/bulletin/categories/"> View all Categories</a>

<div>
{% if latest_notice_list %}
    <br>
    <ol>
    {% for notice in latest_notice_list %}
        <li>  {{notice.upload}} ::::  <a href="/bulletin/categories/{{notice.category.id}}/">{{notice.category}} </a>  :::: <a href="/bulletin/notices/{{ notice.id}}/ "> :  {{ notice.subject}}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No notice is  available.</p>
{% endif %}
</div>

bulletin/templates/bulletin/register.html
<div>
<h3>Register</h3>
<form action="{% url 'bulletin:notices' %}" method="post">
        {% csrf_token %}
        {{ form }}
      

        <input type="submit" name="submit">
</form>
</div>

bulletin/templates/bulletin/starred.html
<div>
{% if notice_list %}
    <h1>Starred Notice</h1>
    <br>
    <ul>
    {% for notice in notice_list %}
        <li>  {{notice.notice.upload}} ::::  <a href="/bulletin/categories/{{notice.categories.id}}/">{{notice.notice.category}} </a>  :::: <a href="/bulletin/notices/{{ notice.notice.id}}/ "> :  {{ notice.notice.subject}}</a></li>
    {% endfor %}
    </ul>	
{% else %}
    <p>No student. Sorry!.</p>
{% endif %}
</div>

bulletin/templates/bulletin/student_detail.html
<h1>Student Detail</h1>
<div>
<a href="/bulletin/students/{{student.id}}/subscribed">Subscribed</a><br>
<a href="/bulletin/students/{{student.id}}/starred">Stared</a>
</div
<div>
<h3>Username : {{ student.user.username }} </h3>
<h3>Name : {{ student.user.first_name }} {{ student.user.last_name }}  </h3>
<h3>Branch: {{ student.branch  }}</h3>
<h3>Enrollment Number: {{ student.enr_no }} </h3>
<h3>Email: {{ student.user.email }}</h3>
</div>

bulletin/templates/bulletin/students.html
<div>
{% if student_list %}
    <h1>Students</h1>
    <br>
    <ul>
    {% for  student in student_list %}
        <li> <&nbsp> {{  student.enr_no }} <&nbsp> <a href="/bulletin/students/{{ student.id }}/">   {{ student.user.username }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No student. Sorry!.</p>
{% endif %}
</div>

bulletin/templates/bulletin/subscribed.html
<div>
{% if subscribed_list %}
    <h1>Subscription</h1>
    <br>
    <ul>
    {% for student in subscribed_list %}
        <li> <a href="/bulletin/categories/{{ student.category.id }}/">   {{ student.category }}</a></li>
    {% endfor %}
    </ul>	
{% else %}
    <p>No student. Sorry!.</p>
{% endif %}
</div>